import os
import sys

os.system('sudo apt update')
os.system('apt install git')
os.system('sudo apt install nodejs')
os.system('sudo apt install npm')
os.system('sudo npm install random-useragent')
os.system('sudo npm install fs')
os.system('sudo npm install url')
os.system('sudo npm install net')
os.system('sudo apt install python3')
os.system('sudo apt install python3-pip')
os.system('sudo pip3 install -r requirements.txt')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print('                                            ')
print(' ▄▄▄· ▄• ▄▌▄▄▄        ▄▄▄   ▄▄▄· ')
print('▐█ ▀█ █▪██▌▀▄ █·▪     ▀▄ █·▐█ ▀█ ')
print('▄█▀▀█ █▌▐█▌▐▀▀▄  ▄█▀▄ ▐▀▀▄ ▄█▀▀█ ')
print('▐█ ▪▐▌▐█▄█▌▐█•█▌▐█▌.▐▌▐█•█▌▐█ ▪▐▌')
print(' ▀  ▀  ▀▀▀ .▀  ▀ ▀█▄▀▪.▀  ▀ ▀  ▀ ')

